basePath: /patterns
layout: pattern
toc:
  - items:
      - index
  - title: Event Storage
    items:
      - event-storage/infinite-retention-event-stream
      - event-storage/compacted-event-stream
      - event-storage/event-store
  - title: Compositional Patterns
    items:
      - compositional-patterns/pipeline
      - compositional-patterns/geo-replication
      - compositional-patterns/event-collaboration
      - compositional-patterns/command-query-responsibility-segregation
  - title: Event Processing
    items:
      - event-processing/event-chunking
      - event-processing/event-processing-application
      - event-processing/event-translator
      - event-processing/claim-check
      - event-processing/event-mapper
      - event-processing/event-splitter
      - event-processing/event-processor
      - event-processing/dead-letter-stream
      - event-processing/event-router
      - event-processing/event-streaming-api
      - event-processing/event-filter
  - title: Event Sink
    items:
      - event-sink/event-sink-connector
      - event-sink/event-sink
  - title: Table
    items:
      - table/projection-table
      - table/state-table
  - title: Stream Processing
    items:
      - stream-processing/wallclock-time
      - stream-processing/event-grouper
      - stream-processing/suppressed-event-aggregator
      - stream-processing/logical-and
      - stream-processing/event-stream-merger
      - stream-processing/wait-for-n-events
      - stream-processing/event-joiner
      - stream-processing/event-time-processing
  - title: Event
    items:
      - event/correlation-identifier
      - event/event
      - event/event-envelope
      - event/event-standardizer
  - title: Event Stream
    items:
      - event-stream/event-stream
      - event-stream/event-broker
  - title: Event Source
    items:
      - event-source/schema-validator
      - event-source/event-source
      - event-source/event-gateway
      - event-source/database-write-aside
      - event-source/database-write-through
      - event-source/event-source-connector
