basePath: /patterns
layout: pattern
toc:
  - items:
      - index
  - title: Event
    items:
      - event/event
      - event/command-event
      - event/correlation-identifier
      - event/data-contract
      - event/event-deserializer
      - event/event-envelope
      - event/event-serializer
      - event/event-standardizer
      - event/schema-on-read
  - title: Event Stream
    items:
      - event-stream/event-stream
      - event-stream/event-broker
      - event-stream/event-streaming-platform
      - event-stream/partitioned-parallelism
      - event-stream/schema-compatibility
      - event-stream/schema-evolution
  - title: Event Source
    items:
      - event-source/event-source
      - event-source/database-write-aside
      - event-source/database-write-through
      - event-source/event-gateway
      - event-source/event-source-connector
      - event-source/schema-validator
  - title: Event Sink
    items:
      - event-sink/event-sink
      - event-sink/event-sink-connector
  - title: Event Storage
    items:
      - event-storage/event-store
      - event-storage/compacted-event-stream
      - event-storage/infinite-retention-event-stream
      - event-storage/limited-retention-event-stream
  - title: Event Processing
    items:
      - event-processing/event-processor
      - event-processing/claim-check
      - event-processing/content-filter
      - event-processing/dead-letter-stream
      - event-processing/event-chunking
      - event-processing/event-filter
      - event-processing/event-mapper
      - event-processing/event-processing-application
      - event-processing/event-router
      - event-processing/event-splitter
      - event-processing/event-streaming-api
      - event-processing/event-translator
      - event-processing/idempotent-writer
      - event-processing/idempotent-reader
  - title: Stream Processing
    items:
      - stream-processing/event-aggregator
      - stream-processing/event-grouper
      - stream-processing/event-joiner
      - stream-processing/event-stream-merger
      - stream-processing/event-time-processing
      - stream-processing/logical-and
      - stream-processing/suppressed-event-aggregator
      - stream-processing/wait-for-n-events
      - stream-processing/wallclock-time
  - title: Table
    items:
      - table/projection-table
      - table/state-table
  - title: Compositional Patterns
    items:
      - compositional-patterns/command-query-responsibility-segregation
      - compositional-patterns/event-collaboration
      - compositional-patterns/geo-replication
      - compositional-patterns/pipeline
      - compositional-patterns/strangler-fig
